/* eslint-disable jsx-a11y/anchor-has-content */
/* eslint-disable jsx-a11y/img-redundant-alt */
/* eslint-disable jsx-a11y/anchor-is-valid */
import React from 'react'

const BlogCardDetail: React.FC = () => {
    return (
        <>
            <div className="mb-16 mx-auto rounded-md overflow-hidden w-[90%] bg-base-100 shadow-sm p-5">
                <div className='header'>
                    <h1 className='text-5xl font-bold mb-5 md:w-[90%]'>Suit Alleges NFL Catalogs Lewd Shots of Women at Games in Database...</h1>
                    <p className='text-xl mb-3 md:w-[80%] text-slate-600'>The league says that some images of female fans and cheerleaders are marked as ‘sensitive’ to make them inaccessible for future productions</p>
                    <p className='font-bold mb-3 text-slate-700'>By Louise Radnofsky, Andrew Beaton</p>
                    <p className='mb-5 text-md text-slate-500'>Feb 28, 2023, 11.05 AM WIB</p>
                    <figure><img src="https://images.wsj.net/im-731228/social" alt="Shoes" className='rounded-md mb-5' /></figure>
                </div>
                <div className='body'>
                    <p className='text-sm text-justify'>As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars] As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]
                        <br /> <br />
                        As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]
                        <br /> <br />
                        As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]
                        <br /> <br />
                        As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]
                        <br /> <br />
                        As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]
                        As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]As the National Football Leagues official production arm, NFL Films has long generated popular content that chronicles the history of Americas most popular sport from an up-close, behind-the-scenes p… [+710 chars]
                    </p>
                </div>
            </div>
        </>
    )
}

export default BlogCardDetail;